<?php

use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function parc_interactive_map_theme() {
  return [
    'parc_interactive_map' => [
      'variables' => [
        'map_id' => FALSE,
      ],
    ],
    'facets_result_item_with_children' => [
      'variables' => [
        'facet' => NULL,
        'raw_value' => '',
        'value' => '',
        'show_count' => FALSE,
        'count' => NULL,
        'is_active' => FALSE,
        'parent_id' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function parc_interactive_map_preprocess_node(&$variables) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['elements']['#node'];

  if (!$node instanceof NodeInterface) {
    return;
  }

  if ($node->bundle() !== 'institution') {
    return;
  }

  if ($variables['view_mode'] == 'teaser') {
    $variables['attributes']['id'] = 'institution-' . $node->id();

    if ($node->hasField('field_media_image')
      && $node->get('field_media_image')->isEmpty()) {
      $default_media = \Drupal::entityTypeManager()
        ->getStorage('media')
        ->loadByProperties([
          'uuid' => '15f79f08-9928-44f7-a909-8ff476217a2e',
        ]);
      $default_media = reset($default_media);

      // Intentionally not saving the node, we only want to temporarily set
      // the placeholder image so that we can render it.
      $node->set('field_media_image', $default_media);
      $placeholderImage = $node->get('field_media_image')->view('teaser');
      $variables['content']['field_media_image'] = $placeholderImage;
    }
  }
}
