<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function parc_interactive_map_theme() {
  return [
    'parc_interactive_map' => [
      'variables' => [
        'map_id' => FALSE,
      ],
    ],
    'facets_result_item_with_children' => [
      'variables' => [
        'facet' => NULL,
        'raw_value' => '',
        'value' => '',
        'show_count' => FALSE,
        'count' => NULL,
        'is_active' => FALSE,
        'parent_id' => NULL,
      ],
    ],
  ];
}
