on:
  push:
    branches:
      - 'devel_migration'

name: 'Deploy staging instance'
jobs:
  deploy:
    name: 'deployment'
    runs-on:
      labels: 'drupal-runner-v2'
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 'Install dependencies'
        uses: eaudeweb/drupal-install-action@v1.1
        with:
          dev: false
          php: /usr/bin/php8.2

      - name: 'Create release archive'
        id: artifact
        uses: eaudeweb/drupal-artifact-action@1.x

      - name: 'Deploy release on the server'
        uses: eaudeweb/drupal-deploy-action@v2.1.2
        with:
          ssh_user:             ${{ secrets.DEVEL_SSH_USER }}
          ssh_host:             ${{ secrets.NEW_DEVEL_SSH_HOST }}
          ssh_key:              ${{ secrets.DEVEL_SSH_KEY }}
          release_id:           ${{ steps.artifact.outputs.base }}
          release_filename:     ${{ steps.artifact.outputs.filename }}
          project_dir:          /var/www/html/devel.eu-parc.eu
          artifacts_dir:        /var/www/artifacts/devel.eu-parc.eu
          settings_file:        /var/www/config/devel.eu-parc.eu/settings.local.php
          public_files_dir:     /var/www/config/devel.eu-parc.eu/files
          # env_file:           /var/www/config/devel.eu-parc.eu/.env
          robo_file:            /var/www/config/devel.eu-parc.eu/robo.yml
          database_dump_dir:    /var/www/config/devel.eu-parc.eu/sync
          artifacts_lifespan: 30

      - name: 'Update the Drupal instance'
        id: release
        uses: eaudeweb/drupal-update-action@v1.0
        with:
          path: /var/www/html/devel.eu-parc.eu
