on:
  workflow_dispatch:

name: 'Dump test SQL database'
jobs:
  deploy:
    name: 'Dump SQL database'
    runs-on: self-hosted
    steps:
      - name: 'Dump SQL database'
        uses: eaudeweb/drupal-sql-dump-action@1.x
        with:
          ssh_user:             ${{ secrets.DEVEL_SSH_USER }}
          ssh_host:             ${{ secrets.DEVEL_SSH_HOST }}
          ssh_key:              ${{ secrets.DEVEL_SSH_KEY }}
          project_dir:          /var/www/html/devel.eu-parc.eu
          sql_dump_file:        /var/www/config/devel.eu-parc.eu/sync/database.sql
